import { Skill } from "@/types";

export const skills: Skill[] = [
  {
    category: "Programming Languages",
    items: ["C", "C++", "Python", "Bash"],
  },
  {
    category: "Embedded Systems",
    items: [
      "Embedded Linux",
      "RTOS",
      "Device Driver Development",
      "BSP Integration",
      "Interrupt Handling",
      "Memory Management",
      "Bootloader Development",
      "Firmware Debugging & Optimization",
      "Yocto",
      "Buildroot",
      "Cross-Compilation Toolchains",
      "IPC Mechanisms",
      "I2C",
      "SPI",
      "UART",
      "Ethernet",
      "Bluetooth",
      "Scope",
      "CMake",
      "BIOS",
    ],
  },
  {
    category: "Networking & Data Plane",
    items: [
      "TCP/IP",
      "Ethernet Switching & Routing",
      "Layer 2 / Layer 3 Networking",
      "Packet Processing Pipelines",
      "DMA Optimization",
      "Network Telemetry",
    ],
  },
  {
    category: "Edge AI & NVIDIA Platforms",
    items: [
      "CUDA",
      "TensorRT",
      "cuDNN",
      "ONNX",
      "NVIDIA Jetson (Xavier, Orin)",
      "JetPack SDK",
      "DeepStream",
      "Nsight Systems",
    ],
  },
  {
    category: "Security & Reliability",
    items: [
      "Secure Boot",
      "Firmware Authentication",
      "MISRA-C Compliance",
      "Static Analysis",
      "JTAG Debugging",
      "Fault Injection & Stress Testing",
      "CI/CD for Embedded Systems",
    ],
  },
  {
    category: "Hardware",
    items: [
      "NVIDIA Jetson Platforms",
      "BlueField DPUs",
      "Raspberry Pi",
      "ESP32",
      "BeagleBone Black",
      "STM32",
    ],
  },
  {
    category: "Design Software",
    items: [
      "Gazebo",
      "MuJoCo",
      "QGroundControl",
      "VS Code",
      "Cursor",
      "Eclipse IDE",
    ],
  },
  {
    category: "Tools & Infrastructure",
    items: [
      "Git",
      "GitHub",
      "Docker",
      "CI/CD",
      "Claude Code",
      "Codex",
      "Vercel",
    ],
  },
  {
    category: "Web & Full Stack",
    items: [
      "Next.js",
      "React",
      "FastAPI",
      "Supabase",
      "PostgreSQL",
      "Tailwind CSS",
    ],
  },
];
